pull_request_rules:
  - name: Security update by dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
  - name: Close all on main
    conditions:
      - base=main
    actions:
      close:
        message: Please do not open PR's on the `main` branch, but on the `develop` branch only. Thank you!
