pull_request_rules:
  - name: Security update by dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
  - name: Close all on main
    conditions:
      - base=main
    actions:
      close:
        message: Do not open PR's on the main branch.
