language: php
sudo: false


php:
  - 5.6
  - 7

install:
  - composer install
  - php artisan env
  - mv -v .env.testing .env
  - php artisan env
  - touch storage/database/testing.db
  - php artisan migrate --seed

script:
  - phpunit
