language: php
sudo: false


php:
  - 7
before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer selfupdate
  - rm composer.lock
  - composer update --no-scripts
  - php artisan clear-compiled
  - php artisan optimize
  - php artisan env
  - mv -v .env.testing .env
  - php artisan env
  - touch storage/upload/at-1.data
  - touch storage/upload/at-2.data
  - touch storage/database/testing.db
  - php artisan migrate --seed

script:
  - phpunit
