# Supabase Local Development Stack
# This file sets up a complete Supabase environment locally

networks:
  supabase_network:
    external: true

volumes:
  db_data:
  storage_data:

services:
  # PostgreSQL Database
  db:
    image: supabase/postgres:15.1.0.147
    hostname: db
    container_name: supabase_db
    restart: unless-stopped
    networks:
      - supabase_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: 5432
      POSTGRES_PORT: 5432
      PGPASSWORD: your-super-secret-and-long-postgres-password
      POSTGRES_PASSWORD: your-super-secret-and-long-postgres-password
      PGDATABASE: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_INITDB_ARGS: --auth-local=trust --auth-host=md5 --encoding=UTF8 --locale=C
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal

  # Kong API Gateway
  kong:
    image: kong:2.8.1
    hostname: kong
    container_name: supabase_kong
    restart: unless-stopped
    networks:
      - supabase_network
    ports:
      - "8000:8000/tcp"
      - "8443:8443/tcp"
    depends_on:
      db:
        condition: service_healthy
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    volumes:
      - ./volumes/api/kong.yml:/var/lib/kong/kong.yml:ro

  # Supabase Auth
  auth:
    image: supabase/gotrue:v2.143.0
    hostname: auth
    container_name: supabase_auth
    restart: unless-stopped
    networks:
      - supabase_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://localhost:8000
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:your-super-secret-and-long-postgres-password@db:5432/postgres
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: ""
      GOTRUE_DISABLE_SIGNUP: false
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      GOTRUE_EXTERNAL_EMAIL_ENABLED: true
      GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: false
      GOTRUE_MAILER_AUTOCONFIRM: false
      GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED: true
      GOTRUE_MAILER_OTP_EXP: 86400
      GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify
      GOTRUE_MAILER_SUBJECTS_INVITE: You have been invited
      GOTRUE_MAILER_SUBJECTS_CONFIRMATION: Confirm Your Signup
      GOTRUE_MAILER_SUBJECTS_RECOVERY: Reset Your Password
      GOTRUE_MAILER_SUBJECTS_EMAIL_CHANGE: Confirm Email Change
      GOTRUE_MAILER_TEMPLATES_INVITE: ./web/auth/invite.html
      GOTRUE_MAILER_TEMPLATES_CONFIRMATION: ./web/auth/confirmation.html
      GOTRUE_MAILER_TEMPLATES_RECOVERY: ./web/auth/recovery.html
      GOTRUE_MAILER_TEMPLATES_EMAIL_CHANGE: ./web/auth/email_change.html
      GOTRUE_SMTP_HOST: inbucket
      GOTRUE_SMTP_PORT: 2500
      GOTRUE_SMTP_USER: ""
      GOTRUE_SMTP_PASS: ""
      GOTRUE_SMTP_ADMIN_EMAIL: admin@email.com
      GOTRUE_RATE_LIMIT_EMAIL_SENT: 3600
      MFA_ENABLED: false

  # Supabase REST API
  rest:
    image: postgrest/postgrest:v12.0.1
    hostname: rest
    container_name: supabase_rest
    restart: unless-stopped
    networks:
      - supabase_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://authenticator:your-super-secret-and-long-postgres-password@db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      PGRST_APP_SETTINGS_JWT_EXP: 3600
    command:
      - postgrest

  # Supabase Studio (Web Interface)
  studio:
    image: supabase/studio:20240326-5e5586d
    hostname: studio
    container_name: supabase_studio
    restart: unless-stopped
    networks:
      - supabase_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: your-super-secret-and-long-postgres-password
      DEFAULT_ORGANIZATION_NAME: Default Organization
      DEFAULT_PROJECT_NAME: Default Project
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: http://localhost:8000
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    ports:
      - "3000:3000"

  # SMTP Server (for local email testing)
  inbucket:
    image: inbucket/inbucket:3.0.3
    hostname: inbucket
    container_name: supabase_inbucket
    restart: unless-stopped
    networks:
      - supabase_network
    environment:
      INBUCKET_WEB_ADDR: 0.0.0.0:9000
      INBUCKET_POP3_ADDR: 0.0.0.0:9110
      INBUCKET_SMTP_ADDR: 0.0.0.0:2500
    ports:
      - "9000:9000"
