name: "Issues - Command to close duplicate issues"

# the workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  checks: read

jobs:
  close_duplicates:
    runs-on: ubuntu-latest
    steps:
      - uses: github/command@v1.1.0
        id: command
        with:
          allowed_contexts: "issue"
          command: ".duplicate"
      - name: reply
        if: ${{ steps.command.outputs.continue == 'true' }}
        run: |
          gh issue comment "$NUMBER" --body 'Hi there!

          This is an automatic reply. `Share and enjoy`.

          This issue is probably a duplicate of issue #${{ steps.command.outputs.params }}. This issue probably refers to the same bug or feature request as your issue.

          Please refer to that issue for support.

          Thank you for your contribution.'

          gh issue close "$NUMBER" --reason completed
          gh issue lock "$NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
