name: 'Issues - Respond to hidden commands'

# the workflow to execute on is comments that are newly created
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

# permissions needed for reacting to IssueOps commands on issues and PRs
permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: read

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ISSUE_BODY=$(gh issue view 8380 --json body)
          if [[ $ISSUE_BODY == *".eOxNZAmyGz6CXMyf"* ]]; then
            gh issue edit "$NUMBER" --add-label "$LABELS"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: v2-layout-issue
      - uses: dessant/label-actions@v4
